### ISSUE TITLE
a problem with predict.py

### ISSUE THREAD

**Issue by 1640477469** [HINTLab/FracNet#12]
hi,i have a problem when i run predict.py.
I have train successfully,and can run predict.py before,but when i want to run another fracnet code in github(by another people),i download torchio,update numpy and torch ,i get a problem with predict.py.
Even  rebuilt a new envs with your code which i have successfully run brfore,it still have the same pronlem.Can you help me to solve lt?thanks for  your help.
![image](https://user-images.githubusercontent.com/98088542/167287096-519d50df-f55e-400f-8c60-c3fcefa5a2fc.png)
![image](https://user-images.githubusercontent.com/98088542/167287270-9050c861-0003-4c97-887b-5167a2287bd7.png)
![image](https://user-images.githubusercontent.com/98088542/167287280-0345d0f3-1698-49f6-8b30-abc105fa410e.png)

**Comment by 1640477469** [comment]
> hi,i have a problem when i run predict.py. I have train successfully,and can run predict.py before,but when i want to run another fracnet code in github(by another people),i download torchio,update numpy and torch ,i get a problem with predict.py. Even rebuilt a new envs with your code which i have successfully run brfore,it still have the same pronlem.Can you help me to solve lt?thanks for your help. ![image](https://user-images.githubusercontent.com/98088542/167287096-519d50df-f55e-400f-8c60-c3fcefa5a2fc.png) ![image](https://user-images.githubusercontent.com/98088542/167287270-9050c861-0003-4c97-887b-5167a2287bd7.png) ![image](https://user-images.githubusercontent.com/98088542/167287280-0345d0f3-1698-49f6-8b30-abc105fa410e.png)

**Comment by KevinWuang** [comment]
你好请问解决了吗，可以交流一下吗
